lang: ruby
sudo: false
notifications:
  email: false
script:
  - bundle exec rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby
  - rbx-3
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
